export type BlockCategory =
  | 'anchor'
  | 'spiritual'
  | 'work'
  | 'study'
  | 'home'
  | 'family'
  | 'health'
  | 'review'
  | 'rest'
  | 'focus'
  | 'custom'

export interface ScheduleBlock {
  id: string
  title: string
  start: string
  end?: string
  category: BlockCategory
  note?: string
  autoGenerated?: boolean
}

export interface DayTemplate {
  weekday: number
  title: string
  summary: string
  mood: string
  blocks: ScheduleBlock[]
  prompts: string[]
}

export interface HabitDefinition {
  id: string
  title: string
  description: string
  group: 'anchors' | 'minimums' | 'growth'
}

export interface QuickTask {
  id: string
  dateKey: string
  title: string
  category: BlockCategory
  durationLabel?: string
}

export interface FocusSession {
  id: string
  dateKey: string
  durationMinutes: number
  sound: Soundscape
  completedAt: string
}

export type Soundscape = 'cosmic' | 'brown' | 'rain' | 'pulse' | 'silent'
